version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_back
    ports:
      - '8282:80'
    restart: unless-stopped
    volumes:
      - ./:/var/www

#mysql :
  db:
    image: 'mariadb'
    container_name: container_db
    ports:
      - '3307'
    restart: always
    environment:
      MYSQL_DATABASE: NAME
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql


#postgres :
  #db:
    #image: postgres:15
    #container_name: container_db
    #restart: always
    #environment:
      #POSTGRES_DB: NAME
      #POSTGRES_USER: user
      #POSTGRES_PASSWORD: password
    #volumes:
      #- db-data:/var/lib/postgresql/data

volumes:
  db-data:
